#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_path="$repo_root/docs/k3s-health.md"
generated_at="$(date -u '+%Y-%m-%d %H:%M UTC')"
namespace="${K3S_NAMESPACE:-default}"
label_selector="${K3S_LABEL_SELECTOR:-}"
kubectl_bin="${KUBECTL_BIN:-kubectl}"

write_placeholder() {
  cat >"$output_path" <<EOF
---
title: K3s Pod Health
---

# K3s Pod Health

> This page is generated by \`scripts/generate-k3s-health.sh\`.
> It shows a build-time snapshot of Kubernetes pod health for DocFX.

_Generated at $generated_at._

Cluster access is not configured for the GitHub Pages build.

To enable live snapshots during the build, configure:

- GitHub secret \`K3S_KUBECONFIG\` with the kubeconfig content for the target cluster
- Optional variable \`K3S_NAMESPACE\` (defaults to \`default\`)
- Optional variable \`K3S_LABEL_SELECTOR\` to filter the reported workloads

When configured, this page will include the latest \`kubectl get pods\` and deployment snapshot from the cluster at build time.
EOF
}

if [[ -n "${KUBECONFIG:-}" ]]; then
  if [[ ! -f "$KUBECONFIG" ]]; then
    write_placeholder
    exit 0
  fi
elif [[ ! -f "$HOME/.kube/config" ]]; then
  write_placeholder
  exit 0
fi

scope_args=()
scope_label="Namespace: \`$namespace\`"
if [[ "$namespace" == "all" ]]; then
  scope_args=(-A)
  scope_label="Namespace scope: all namespaces"
else
  scope_args=(-n "$namespace")
fi

selector_line=""
if [[ -n "$label_selector" ]]; then
  selector_line="_Label selector: \`$label_selector\`._"
  pods_output="$("$kubectl_bin" get pods "${scope_args[@]}" -l "$label_selector")"
  deployments_output="$("$kubectl_bin" get deployments "${scope_args[@]}" -l "$label_selector" 2>&1 || true)"
else
  pods_output="$("$kubectl_bin" get pods "${scope_args[@]}")"
  deployments_output="$("$kubectl_bin" get deployments "${scope_args[@]}" 2>&1 || true)"
fi

cat >"$output_path" <<EOF
---
title: K3s Pod Health
---

# K3s Pod Health

> This page is generated by \`scripts/generate-k3s-health.sh\`.
> It shows a build-time snapshot of Kubernetes pod health for DocFX.

_Generated at $generated_at._

$scope_label

${selector_line}

## Pods

\`\`\`text
$pods_output
\`\`\`

## Deployments

\`\`\`text
$deployments_output
\`\`\`
EOF
